### PR TITLE
Proxy params to via are positional arguments. 

### PR DESCRIPTION
**Pull request by mdayaram**
The current proxy configuration never worked.

Documentation from HTTP.rb on proxy support: https://github.com/httprb/http/wiki/Proxy-Support

### CODE REVIEW

**Review by horgh — APPROVED** [review]
Thank you!

**Comment by mdayaram** [comment]
Thanks for merging! Do you know when the next release will be? I'd like to use this update on our app.

**Comment by horgh** [comment]
I just released it :).

**Comment by mdayaram** [comment]
yay! thank you!

**Pull request merged**
